name: Post latest RSS item to Telegram

on:
  push:
    paths:
      - jaunumi.json
      - generate_rss.js
      - jaunumi.xml

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # (1) Instalē atkarību xmlbuilder (vai citas, ja vajag)
      - name: Install RSS dependencies
        run: npm install xmlbuilder

      # (2) Ģenerē RSS un HTML (ja tāds ir)
      - name: Build RSS and HTML
        run: node generate_rss.js

      # (3) Nolasīt jaunāko ierakstu no jaunumi.xml
      - id: latest
        run: |
          title=$(xmllint --xpath "string(//item[1]/title)" jaunumi.xml)
          link=$(xmllint --xpath "string(//item[1]/guid)" jaunumi.xml)
          guid=$link
          echo "title=$title" >> $GITHUB_OUTPUT
          echo "link=$link"   >> $GITHUB_OUTPUT
          echo "guid=$guid"   >> $GITHUB_OUTPUT

      # (4) Pārbauda, vai šis GUID jau ziņots (saglabāts failā)
      - id: check
        run: |
          prev=$(cat .github/latest_guid 2>/dev/null || echo "none")
          if [ "$prev" = "${{ steps.latest.outputs.guid }}" ]; then
            echo "send=no" >> $GITHUB_OUTPUT
          else
            echo "send=yes" >> $GITHUB_OUTPUT
          fi

      # (5) Ja jauns — sūtīt uz Telegram
      - name: Send to Telegram
        if: steps.check.outputs.send == 'yes'
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
        run: |
          node send_telegram.js \
               "${{ steps.latest.outputs.title }}" \
               "${{ steps.latest.outputs.link }}"

      # (6) Saglabā šo GUID, lai citreiz nesūta to pašu
      - name: Save latest GUID
        if: steps.check.outputs.send == 'yes'
        run: |
          echo "${{ steps.latest.outputs.guid }}" > .github/latest_guid
          git config user.name github-actions
          git config user.email github@users.noreply.github.com
          git add .github/latest_guid
          git commit -m "Update latest_guid" && git push || true
