name: Generate RSS

on:
  push:
    paths:
      - 'jaunumi.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate RSS
        run: |
          npm install xmlbuilder
          node generate_rss.js

      - name: Commit RSS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add jaunumi.xml
          git commit -m "Atjaunināts RSS"
          git push
